//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Project/PlayerInputs/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""0c967b55-e2ed-4304-83e9-435df3a86b2f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Button"",
                    ""id"": ""820afd6b-5191-415f-ab1a-030e82210eb4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""f5544ec6-3e26-4948-b990-274d5d452c87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonSpell 1"",
                    ""type"": ""Button"",
                    ""id"": ""aea0fac7-9a14-440c-8467-70f6605b4654"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonSpell 2"",
                    ""type"": ""Button"",
                    ""id"": ""0a0de187-03a8-4f1c-8b4a-f2788180a5ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonSpell 3"",
                    ""type"": ""Button"",
                    ""id"": ""55389bea-5c77-4560-a2a7-b3bf27b92851"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonSpell 4"",
                    ""type"": ""Button"",
                    ""id"": ""2bcb511c-6704-4ed1-ab71-fc08be9c6248"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerSpell 1"",
                    ""type"": ""Button"",
                    ""id"": ""09fd2924-2fd0-4ff0-a6d4-061f2de00235"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerSpell 2"",
                    ""type"": ""Button"",
                    ""id"": ""11295637-9495-48f4-83d5-0e5d23547839"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerSpell 3"",
                    ""type"": ""Button"",
                    ""id"": ""3702b3c6-c72d-4a4a-89e2-e28ad6eb2974"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerSpell 4"",
                    ""type"": ""Button"",
                    ""id"": ""2fd539de-eb19-431e-ac96-a31550e33d64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7f20414d-0d2d-4fcd-81fe-318f46e900cf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a6e50a4-d31b-433e-9b35-1132ee746d80"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""480e8d19-8394-4dc3-b08b-228f4ee43656"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonSpell 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3e62964-abe1-4626-8407-20b852e9a18f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonSpell 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6e222d0-4242-462e-b8c6-e537ef2e837f"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonSpell 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6916c8f-c567-4c88-8405-eca75aaa8925"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonSpell 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b26cb63a-9a5a-4dd4-ad33-8242eb6de285"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerSpell 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2d0f7e1-00fd-4f4b-814e-f5d4013830cc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerSpell 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8705c88b-eca6-474f-8fb8-dcf812b6e24d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerSpell 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3647b4fb-bd2f-4b3e-83a0-5a175e7b88a6"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerSpell 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Movement = m_Gameplay.FindAction("Movement", throwIfNotFound: true);
        m_Gameplay_Inventory = m_Gameplay.FindAction("Inventory", throwIfNotFound: true);
        m_Gameplay_SummonSpell1 = m_Gameplay.FindAction("SummonSpell 1", throwIfNotFound: true);
        m_Gameplay_SummonSpell2 = m_Gameplay.FindAction("SummonSpell 2", throwIfNotFound: true);
        m_Gameplay_SummonSpell3 = m_Gameplay.FindAction("SummonSpell 3", throwIfNotFound: true);
        m_Gameplay_SummonSpell4 = m_Gameplay.FindAction("SummonSpell 4", throwIfNotFound: true);
        m_Gameplay_PlayerSpell1 = m_Gameplay.FindAction("PlayerSpell 1", throwIfNotFound: true);
        m_Gameplay_PlayerSpell2 = m_Gameplay.FindAction("PlayerSpell 2", throwIfNotFound: true);
        m_Gameplay_PlayerSpell3 = m_Gameplay.FindAction("PlayerSpell 3", throwIfNotFound: true);
        m_Gameplay_PlayerSpell4 = m_Gameplay.FindAction("PlayerSpell 4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Movement;
    private readonly InputAction m_Gameplay_Inventory;
    private readonly InputAction m_Gameplay_SummonSpell1;
    private readonly InputAction m_Gameplay_SummonSpell2;
    private readonly InputAction m_Gameplay_SummonSpell3;
    private readonly InputAction m_Gameplay_SummonSpell4;
    private readonly InputAction m_Gameplay_PlayerSpell1;
    private readonly InputAction m_Gameplay_PlayerSpell2;
    private readonly InputAction m_Gameplay_PlayerSpell3;
    private readonly InputAction m_Gameplay_PlayerSpell4;
    public struct GameplayActions
    {
        private @PlayerInputs m_Wrapper;
        public GameplayActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Gameplay_Movement;
        public InputAction @Inventory => m_Wrapper.m_Gameplay_Inventory;
        public InputAction @SummonSpell1 => m_Wrapper.m_Gameplay_SummonSpell1;
        public InputAction @SummonSpell2 => m_Wrapper.m_Gameplay_SummonSpell2;
        public InputAction @SummonSpell3 => m_Wrapper.m_Gameplay_SummonSpell3;
        public InputAction @SummonSpell4 => m_Wrapper.m_Gameplay_SummonSpell4;
        public InputAction @PlayerSpell1 => m_Wrapper.m_Gameplay_PlayerSpell1;
        public InputAction @PlayerSpell2 => m_Wrapper.m_Gameplay_PlayerSpell2;
        public InputAction @PlayerSpell3 => m_Wrapper.m_Gameplay_PlayerSpell3;
        public InputAction @PlayerSpell4 => m_Wrapper.m_Gameplay_PlayerSpell4;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
            @SummonSpell1.started += instance.OnSummonSpell1;
            @SummonSpell1.performed += instance.OnSummonSpell1;
            @SummonSpell1.canceled += instance.OnSummonSpell1;
            @SummonSpell2.started += instance.OnSummonSpell2;
            @SummonSpell2.performed += instance.OnSummonSpell2;
            @SummonSpell2.canceled += instance.OnSummonSpell2;
            @SummonSpell3.started += instance.OnSummonSpell3;
            @SummonSpell3.performed += instance.OnSummonSpell3;
            @SummonSpell3.canceled += instance.OnSummonSpell3;
            @SummonSpell4.started += instance.OnSummonSpell4;
            @SummonSpell4.performed += instance.OnSummonSpell4;
            @SummonSpell4.canceled += instance.OnSummonSpell4;
            @PlayerSpell1.started += instance.OnPlayerSpell1;
            @PlayerSpell1.performed += instance.OnPlayerSpell1;
            @PlayerSpell1.canceled += instance.OnPlayerSpell1;
            @PlayerSpell2.started += instance.OnPlayerSpell2;
            @PlayerSpell2.performed += instance.OnPlayerSpell2;
            @PlayerSpell2.canceled += instance.OnPlayerSpell2;
            @PlayerSpell3.started += instance.OnPlayerSpell3;
            @PlayerSpell3.performed += instance.OnPlayerSpell3;
            @PlayerSpell3.canceled += instance.OnPlayerSpell3;
            @PlayerSpell4.started += instance.OnPlayerSpell4;
            @PlayerSpell4.performed += instance.OnPlayerSpell4;
            @PlayerSpell4.canceled += instance.OnPlayerSpell4;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
            @SummonSpell1.started -= instance.OnSummonSpell1;
            @SummonSpell1.performed -= instance.OnSummonSpell1;
            @SummonSpell1.canceled -= instance.OnSummonSpell1;
            @SummonSpell2.started -= instance.OnSummonSpell2;
            @SummonSpell2.performed -= instance.OnSummonSpell2;
            @SummonSpell2.canceled -= instance.OnSummonSpell2;
            @SummonSpell3.started -= instance.OnSummonSpell3;
            @SummonSpell3.performed -= instance.OnSummonSpell3;
            @SummonSpell3.canceled -= instance.OnSummonSpell3;
            @SummonSpell4.started -= instance.OnSummonSpell4;
            @SummonSpell4.performed -= instance.OnSummonSpell4;
            @SummonSpell4.canceled -= instance.OnSummonSpell4;
            @PlayerSpell1.started -= instance.OnPlayerSpell1;
            @PlayerSpell1.performed -= instance.OnPlayerSpell1;
            @PlayerSpell1.canceled -= instance.OnPlayerSpell1;
            @PlayerSpell2.started -= instance.OnPlayerSpell2;
            @PlayerSpell2.performed -= instance.OnPlayerSpell2;
            @PlayerSpell2.canceled -= instance.OnPlayerSpell2;
            @PlayerSpell3.started -= instance.OnPlayerSpell3;
            @PlayerSpell3.performed -= instance.OnPlayerSpell3;
            @PlayerSpell3.canceled -= instance.OnPlayerSpell3;
            @PlayerSpell4.started -= instance.OnPlayerSpell4;
            @PlayerSpell4.performed -= instance.OnPlayerSpell4;
            @PlayerSpell4.canceled -= instance.OnPlayerSpell4;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnSummonSpell1(InputAction.CallbackContext context);
        void OnSummonSpell2(InputAction.CallbackContext context);
        void OnSummonSpell3(InputAction.CallbackContext context);
        void OnSummonSpell4(InputAction.CallbackContext context);
        void OnPlayerSpell1(InputAction.CallbackContext context);
        void OnPlayerSpell2(InputAction.CallbackContext context);
        void OnPlayerSpell3(InputAction.CallbackContext context);
        void OnPlayerSpell4(InputAction.CallbackContext context);
    }
}
